apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: node-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-container
          image: errorhunter/node-application:bf02479e68abcbcb18b6cd93c2e1e40bfecc92c8
          ports:
            - containerPort: 8080
