apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: node-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-container
          image: errorhunter/node-application:1a757f3ae64a9e262e05d82c8dde7ba833986548
          ports:
            - containerPort: 8080
