name: Docker Build and Push with GitOps Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  pull_request:  # Optional: Trigger on pull requests
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Set up Docker Buildx (for multi-platform builds if needed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build and push the Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/node-application:${{ github.sha }}

    # Update Kubernetes manifests using yq
    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq

    - name: Update GitOps
      run: |
        yq eval ".spec.template.spec.containers[0].image = \"${{ secrets.DOCKER_USERNAME }}/node-application:${{ github.sha }}\"" -i k8s/Deployment.yaml

    # Commit and push updated manifests to the GitOps repo
    - name: Commit and Push GitOps
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add k8s/Deployment.yaml
        git commit -m "Update image to ${{ secrets.DOCKER_USERNAME }}/node-application:${{ github.sha }}"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
